### ISSUE TITLE
Constants+URLs.swift, absolute path breaks build

### ISSUE THREAD

**Issue by reedb** [erikmartens/NearbyWeather#89] opened 2020-01-31 03:41 UTC
./project.pbxproj:175:

Currently:
F2E7237E23E0EA65001189F5 /* Constants+URLs.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; name = "Constants+URLs.swift"; path = "/Users/erikmartens/Code/NearbyWeather/NearbyWeather/Constants+URLs.swift"; sourceTree = "<absolute>"; };

Should be:
F2E7237E23E0EA65001189F5 /* Constants+URLs.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = "Constants+URLs.swift"; sourceTree = "<group>"; };

**Comment by reedb** [comment] 2020-01-31 03:44
Very small change needed to remove absolute path in:
   .../NearbyWeather/NearbyWeather.xcodeproj/project.pbxproj
Thanks, -Reed

**Comment by erikmartens** [comment] 2020-01-31 10:43
Thanks, I have already noticed this as well in my latest TF build. Will merge a fix tonight.

**Comment by erikmartens** [comment] 2020-01-31 20:23
@reedb The issue is now fixed

**Closed** 2020-01-31 20:22 UTC
Labels: Bugfix
